# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [3]:
X

AT      V       AP     RH
0     14.96  41.76  1024.07  73.17
1     25.18  62.96  1020.04  59.08
2      5.11  39.40  1012.16  92.14
3     20.86  57.32  1010.24  76.64
4     10.82  37.50  1009.23  96.62
...     ...    ...      ...    ...
9563  16.65  49.69  1014.01  91.00
9564  13.19  39.18  1023.67  66.78
9565  31.32  74.33  1012.92  36.48
9566  24.48  69.45  1013.86  62.39
9567  21.60  62.52  1017.23  67.87

[9568 rows x 4 columns]

In [4]:
y

0       463.26
1       444.37
2       488.56
3       446.48
4       473.90
         ...  
9563    460.03
9564    469.62
9565    429.57
9566    435.74
9567    453.28
Name: PE, Length: 9568, dtype: float64

In [5]:
print(X)
print(y)

         AT      V       AP     RH
0     14.96  41.76  1024.07  73.17
1     25.18  62.96  1020.04  59.08
2      5.11  39.40  1012.16  92.14
3     20.86  57.32  1010.24  76.64
4     10.82  37.50  1009.23  96.62
...     ...    ...      ...    ...
9563  16.65  49.69  1014.01  91.00
9564  13.19  39.18  1023.67  66.78
9565  31.32  74.33  1012.92  36.48
9566  24.48  69.45  1013.86  62.39
9567  21.60  62.52  1017.23  67.87

[9568 rows x 4 columns]
0       463.26
1       444.37
2       488.56
3       446.48
4       473.90
         ...  
9563    460.03
9564    469.62
9565    429.57
9566    435.74
9567    453.28
Name: PE, Length: 9568, dtype: float64


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann =  tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 205563.1719
Epoch 2/100
240/240 [==============================] - 0s 881us/step - loss: 195733.7969
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 152907.3438
Epoch 4/100
240/240 [==============================] - 0s 895us/step - loss: 92352.6797
Epoch 5/100
240/240 [==============================] - 0s 938us/step - loss: 54817.3320
Epoch 6/100
240/240 [==============================] - 0s 920us/step - loss: 33449.9922
Epoch 7/100
240/240 [==============================] - 0s 904us/step - loss: 19997.7344
Epoch 8/100
240/240 [==============================] - 0s 905us/step - loss: 12903.1523
Epoch 9/100
240/240 [==============================] - 0s 860us/step - loss: 8956.6660
Epoch 10/100
240/240 [==============================] - 0s 847us/step - loss: 6257.5586
Epoch 11/100
240/240 [==============================] - 0s 896us/step - loss: 4324.1055
Epoch 12/100
240/240 [============

240/240 [==============================] - 0s 1ms/step - loss: 21.4695
Epoch 96/100
240/240 [==============================] - 0s 1ms/step - loss: 21.5729
Epoch 97/100
240/240 [==============================] - 0s 1ms/step - loss: 21.5867
Epoch 98/100
240/240 [==============================] - 0s 1ms/step - loss: 21.4198
Epoch 99/100
240/240 [==============================] - 0s 1ms/step - loss: 21.4501
Epoch 100/100
240/240 [==============================] - ETA: 0s - loss: 21.48 - 0s 971us/step - loss: 21.4090


### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)

In [22]:
y_pred.reshape(-1)

array([430.81, 458.31, 462.32, ..., 469.32, 441.95, 461.4 ], dtype=float32)

In [16]:
y_test

4834    431.23
1768    460.01
2819    461.14
7779    445.90
7065    451.29
         ...  
6452    460.29
794     452.42
627     473.26
3515    438.00
7600    463.28
Name: PE, Length: 1914, dtype: float64

In [23]:
y_test.to_numpy()

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [18]:
type(y_test)

pandas.core.series.Series

In [26]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(-1).reshape(len(y_pred),1), y_test.to_numpy().reshape(len(y_test),1) ),1))

[[430.81 431.23]
 [458.31 460.01]
 [462.32 461.14]
 ...
 [469.32 473.26]
 [441.95 438.  ]
 [461.4  463.28]]


In [27]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test.to_numpy(), y_pred.reshape(-1))

19.992314155007982